import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { 
  Sparkles, 
  X, 
  Copy, 
  Check, 
  AlertTriangle, 
  Send, 
  RefreshCw, 
  FileText,
  BookmarkPlus
} from 'lucide-react';

export const OraclePanel: React.FC = () => {
  const { 
    oracleOpen, 
    setOracleOpen, 
    oracleLoading, 
    oracleResponse, 
    askOracle, 
    addIntelligence,
    opportunity
  } = useApp();

  const [customPrompt, setCustomPrompt] = useState('');
  const [copied, setCopied] = useState(false);
  const [editableText, setEditableText] = useState<string>('');
  const [savedToArchive, setSavedToArchive] = useState(false);

  React.useEffect(() => {
    if (oracleResponse) {
      setEditableText(oracleResponse);
      setSavedToArchive(false);
    }
  }, [oracleResponse]);

  if (!oracleOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(editableText || oracleResponse || '');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveToArchive = () => {
    if (!editableText) return;
    addIntelligence({
      title: `ORACLE Strategic Audit: ${opportunity.name} (${new Date().toISOString().split('T')[0]})`,
      type: 'brief',
      summary: '6-part commercial truth and bottleneck audit generated by ORACLE.',
      fullContent: editableText,
      keyTakeaways: [
        'Commercial reality audit completed',
        'Top bottleneck identified',
        'Decision deadline established'
      ],
      tags: ['ORACLE', 'Strategy', 'Bottleneck', 'Commercial Truth'],
      entities: [opportunity.name],
      linkedProject: opportunity.name,
      sourceTier: 'primary',
      confidence: 'high',
      evidenceStatus: 'approved',
      dataClassification: 'private',
    });
    setSavedToArchive(true);
    setTimeout(() => setSavedToArchive(false), 3000);
  };

  const promptShortcuts = [
    { label: 'Weekly Operating Brief', prompt: 'Provide a blunt weekly operating brief on commercial progress, cash trajectory, and highest-leverage actions.' },
    { label: 'Top Revenue Bottleneck', prompt: 'Audit the exact friction point preventing our product from reaching the $750/month approval threshold.' },
    { label: 'Weak Assumptions & Kill Check', prompt: 'Examine our opportunity scorecard and identify the single most dangerous unvalidated assumption that could require killing the project.' },
    { label: 'Next Paid Experiment', prompt: 'Design the single fastest customer-facing experiment to validate willingness-to-pay within 7 days.' },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-end bg-black/60 backdrop-blur-sm">
      <div className="w-full max-w-2xl h-full bg-[#0a0e17] border-l border-cyan-500/30 shadow-2xl flex flex-col justify-between">
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-[#0d121f]">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded bg-cyan-500/20 border border-cyan-400/40 flex items-center justify-center text-cyan-300">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <div className="text-sm font-bold font-mono tracking-wide text-white flex items-center gap-2">
                <span>ORACLE // Strategy Terminal</span>
                <span className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800/60 font-mono">
                  Skeptical · Evidence-Grounded
                </span>
              </div>
              <div className="text-[11px] text-slate-400 font-mono">
                Active Grounding: {opportunity.name} (Stage: {opportunity.stage})
              </div>
            </div>
          </div>

          <button
            onClick={() => setOracleOpen(false)}
            className="p-1.5 text-slate-400 hover:text-white rounded hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Shortcuts */}
        <div className="px-4 py-2.5 border-b border-slate-800/80 bg-[#080b12] flex items-center gap-2 overflow-x-auto text-xs font-mono">
          <span className="text-slate-400 shrink-0 text-[11px]">Audit Mode:</span>
          {promptShortcuts.map((sc, idx) => (
            <button
              key={idx}
              onClick={() => askOracle(sc.prompt)}
              disabled={oracleLoading}
              className="px-2.5 py-1 text-[11px] bg-slate-800/70 hover:bg-slate-700 text-slate-300 hover:text-cyan-300 border border-slate-700/60 rounded transition-colors whitespace-nowrap"
            >
              {sc.label}
            </button>
          ))}
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4 font-sans text-sm text-slate-200">
          {oracleLoading ? (
            <div className="h-64 flex flex-col items-center justify-center space-y-3">
              <RefreshCw className="w-8 h-8 text-cyan-400 animate-spin" />
              <p className="text-xs font-mono text-cyan-300 tracking-wider">
                SYNTHESIZING DOCKETS & COMMERCIAL CONSTRAINTS...
              </p>
              <p className="text-[11px] text-slate-400 max-w-sm text-center font-mono">
                Evaluating gross margin, unverified claims, and distribution funnel telemetry.
              </p>
            </div>
          ) : oracleResponse ? (
            <div className="space-y-4">
              <div className="flex items-center justify-between text-xs font-mono text-slate-400 pb-2 border-b border-slate-800">
                <span className="text-cyan-400 flex items-center gap-1.5">
                  <Check className="w-3.5 h-3.5" /> 6-Part Venture Strategic Audit
                </span>
                <div className="flex items-center gap-3">
                  <button
                    onClick={handleCopy}
                    className="hover:text-cyan-300 flex items-center gap-1 transition-colors"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button
                    onClick={handleSaveToArchive}
                    className="hover:text-cyan-300 flex items-center gap-1 transition-colors text-slate-300"
                  >
                    <BookmarkPlus className="w-3.5 h-3.5 text-amber-400" />
                    <span>{savedToArchive ? 'Saved!' : 'Save to Archive'}</span>
                  </button>
                </div>
              </div>

              {/* Editable Area */}
              <div className="space-y-2">
                <div className="text-[11px] font-mono text-slate-400">
                  Note: All AI synthesis is fully editable before saving or citing:
                </div>
                <textarea
                  value={editableText}
                  onChange={(e) => setEditableText(e.target.value)}
                  className="w-full h-[400px] p-3.5 bg-[#070a10] border border-slate-800 rounded-md text-xs font-mono text-slate-200 leading-relaxed focus:border-cyan-500/50 focus:outline-none resize-none font-mono"
                  placeholder="ORACLE response..."
                />
              </div>

              {/* Grounding Notice */}
              <div className="p-3 bg-cyan-950/20 border border-cyan-800/40 rounded flex items-start gap-2.5 text-xs text-cyan-200/90 font-mono">
                <FileText className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                <div>
                  <strong>Traceability Note:</strong> ORACLE evaluations are anchored in approved primary regulatory filings and validated customer payment transactions. Unverified inferences are flagged for human audit.
                </div>
              </div>
            </div>
          ) : (
            <div className="h-64 flex flex-col items-center justify-center text-center space-y-3">
              <Sparkles className="w-10 h-10 text-slate-600" />
              <div className="text-sm font-mono text-slate-300">
                ORACLE Strategic Terminal Ready
              </div>
              <p className="text-xs text-slate-400 max-w-md font-sans">
                Ask a specific commercial question or run a standardized venture audit to stress-test economic bottlenecks, evidence gaps, and distribution channels.
              </p>
            </div>
          )}
        </div>

        {/* Input Bar */}
        <div className="p-4 border-t border-slate-800 bg-[#0d121f]">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (customPrompt.trim()) {
                askOracle(customPrompt);
                setCustomPrompt('');
              }
            }}
            className="flex items-center gap-2"
          >
            <input
              type="text"
              value={customPrompt}
              onChange={(e) => setCustomPrompt(e.target.value)}
              placeholder="Ask ORACLE to analyze a bottleneck, pricing test, or kill criterion..."
              className="flex-1 px-3.5 py-2 text-xs font-mono bg-[#070a10] border border-slate-700/80 rounded-md text-slate-100 placeholder-slate-500 focus:border-cyan-400 focus:outline-none"
            />
            <button
              type="submit"
              disabled={oracleLoading || !customPrompt.trim()}
              className="px-4 py-2 text-xs font-mono font-medium text-black bg-cyan-400 hover:bg-cyan-300 disabled:opacity-40 rounded-md transition-colors flex items-center gap-1.5"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Query</span>
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};
